name: Test direct-js

on:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - '**.md'

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node:
          - 18.x
          - 20.x
          - 22.x

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: npm install

      - name: Run smoke tests
        timeout-minutes: 2
        run: |
          node test/login.js "${{ secrets.DIRECT_TESTING_USER }}:${{ secrets.DIRECT_TESTING_PASSWORD }}"
          node test/smoke.js
